Removed Image vomparison against stored images. Not yet reliable working. Added list 680xxx >NIL: to ssh commands. Otherwise wcs executables seems to unvisible to WINUAE. WSL2/Windows_11-ISSUE? - Worked under VirtualBox/Windows10/Samba without this list command.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -239,6 +239,7 @@ popd
 function RenderTest_Generic {
     local LABEL=$1
     local SSH_COMMAND="$2 7462847623"  # magic param
+    local BUILDDIR=$(dirname $2)
     local IMAGE_PREFIX=$3
     local MAX_PIXEL_DIFFER=$4
 
@@ -254,7 +255,8 @@ function RenderTest_Generic {
     # Remote-Ausfuehrung
     Error=0
     ErrorString=""
-    sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && $SSH_COMMAND"
+    # "list $BASENAME" seems to be necessary to make the executable visible to WinUAE???
+    sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && list $BUILDDIR >NIL: && $SSH_COMMAND"
 
     # Montage der Bilder
     montage \
@@ -265,42 +267,42 @@ function RenderTest_Generic {
         -geometry 752x480 -tile 2x2 $IMAGE_PREFIX.jpg
     eog $IMAGE_PREFIX.jpg &
 
-    # Fehlerueberpruefung fuer jede Datei
-    for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
-    do
-
-      # Fuehre den compare-Befehl aus und speichere die Ausgabe in einer Variablen
-#set -x
-      difference=$(compare -metric AE -fuzz 6% test_files/reference/ref_wcs2.031_$file RenderTestImages/$file null: 2>&1)
-
-      # Extrahiere die Differenz von der Ausgabe (da compare Fehlerausgaben als Rueckgabewerte sendet)
-      # In diesem Fall wird die Differenz auf die Standardfehlerausgabe geschrieben, daher "2>&1".
-      # Die Ausgabe ist eine Zahl (die Anzahl der unterschiedlichen Pixel).
-      difference_value=$(echo "$difference" | awk '/^[0-9]+/{print $1}')
-echo "differenz_value=$difference_value"
-      # Vergleiche, ob die Differenz groesser als 10 ist
-      if [ "$(echo "$difference_value > 0" | bc -l)" -ne 0 ]; then
-echo "Diff zu gross"
-        LastError=1
-        Error=$(expr $Error + $LastError)
-
-        if [ $LastError -ne 0 ]; then
-            ErrorString="$ErrorString $file"
-        fi
-else
-echo "Diff nicht groesser 10"
-      fi
-#set +x
-    done
-
-    # Fehlerbehandlung
-    if [ $Error -ne 0 ]; then
-        echo "Local pre-commit hook"
-        echo "$SSH_COMMAND failed ($ErrorString)!"
-#        echo "Commit refused."
-         echo "ignored for now, test will move later."
-#        exit 1
-    fi
+#    # Fehlerueberpruefung fuer jede Datei
+#    for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
+#    do
+#
+#      # Fuehre den compare-Befehl aus und speichere die Ausgabe in einer Variablen
+##set -x
+#      difference=$(compare -metric AE -fuzz 6% test_files/reference/ref_wcs2.031_$file RenderTestImages/$file null: 2>&1)
+#
+#      # Extrahiere die Differenz von der Ausgabe (da compare Fehlerausgaben als Rueckgabewerte sendet)
+#      # In diesem Fall wird die Differenz auf die Standardfehlerausgabe geschrieben, daher "2>&1".
+#      # Die Ausgabe ist eine Zahl (die Anzahl der unterschiedlichen Pixel).
+#      difference_value=$(echo "$difference" | awk '/^[0-9]+/{print $1}')
+#echo "differenz_value=$difference_value"
+#      # Vergleiche, ob die Differenz groesser als 10 ist
+#      if [ "$(echo "$difference_value > 0" | bc -l)" -ne 0 ]; then
+#echo "Diff zu gross"
+#        LastError=1
+#        Error=$(expr $Error + $LastError)
+#
+#        if [ $LastError -ne 0 ]; then
+#            ErrorString="$ErrorString $file"
+#        fi
+#else
+#echo "Diff nicht groesser 10"
+#      fi
+##set +x
+#    done
+#
+#    # Fehlerbehandlung
+#    if [ $Error -ne 0 ]; then
+#        echo "Local pre-commit hook"
+#        echo "$SSH_COMMAND failed ($ErrorString)!"
+##        echo "Commit refused."
+#         echo "ignored for now, test will move later."
+##        exit 1
+#    fi
 }
 
 ################################################################
@@ -315,17 +317,17 @@ function RenderTest_WinUAE_68020 {
 
 ################################################################
 function RenderTest_WinUAE_68020_60 {
-    RenderTest_Generic "68020_60" "68020-60/wcs_68020-60" "Big68020_60" "ref"
+    RenderTest_Generic "68020_60" "68020-60/WCS_68020-60" "Big68020_60" "ref"
 }
 
 ################################################################
 function RenderTest_WinUAE_68040 {
-    RenderTest_Generic "68040" "68040/wcs_68040" "Big68040" "ref"
+    RenderTest_Generic "68040" "68040/WCS_68040" "Big68040" "ref"
 }
 
 ################################################################
 function RenderTest_WinUAE_68060 {
-    RenderTest_Generic "68060" "68060/wcs_68060" "Big68060" "ref"
+    RenderTest_Generic "68060" "68060/WCS_68060" "Big68060" "ref"
 }
 
 ################################################################
