locale AGUI.c done. (some more translations needed)

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -13,6 +13,14 @@ for FILE in $FILE_LIST; do
     fi
 done
 
+# check WCS.cs (SimpleCat) is ISO-8859
+if [ $(file /home/developer/Desktop/SelcoGit/3DNature/Amiga/WCS.cs | grep "ISO-8859") -ne 0 ] then
+   echo "Local pre-commit hook"
+   echo "Error: File $FILE is not ISO-8859 encoded. Change that to ISO 8859-1 for Amiga and try again!"
+   echo "Commit refused."
+   exit 1
+fi
+
 #check, if WCS is still compileable with SAS/C
 cd /home/developer/Desktop/SelcoGit/3DNature/Amiga/
 ./build_wcs_sasc.sh
