work on automatic testing in pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -182,240 +182,98 @@ popd
 
 
 ################################################################
-function RenderTest_WinUAE_SASC {
-# Render-Test SAS/C
+################################################################
+function RenderTest_Generic {
+    local LABEL=$1
+    local SSH_COMMAND=$2
+    local IMAGE_PREFIX=$3
+    local MAX_PIXEL_DIFFER=$4
 
-if [ -z $WINUAEIP ]; then
-   CheckSshWinUAE
-fi
-
-rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-
-# This runs the complete program. At the end we have the rendered example images that need to be checked.
-Error=0
-ErrorString=""
-sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && wcs_test_sasc_render"
-
-montage \
-        -label SAS/C ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
-        -label SAS/C ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
-        -label SAS/C ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
-        -label SAS/C ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
-        -geometry 752x480 -tile 2x2 BigSasC.jpg 
-eog BigSasC.jpg &
-
-
-for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
-do
-  #  cmp ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file ~/Desktop/SelcoGit/3DNature/Amiga/test_files/reference/ref_$file
-  # display ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file  # just diplay each rendered file for now
-    LastError=$?
-    Error=$(expr $Error + $LastError)
-
-    if [ $LastError -ne 0 ]; then
-        ErrorString="$ErrorString $file"
+    if [ -z $WINUAEIP ]; then
+       CheckSshWinUAE
     fi
-done
 
-# Wenn Fehler aufgetreten sind, gebe eine Fehlermeldung aus
-if [ $Error -ne 0 ]; then
-   echo "Local pre-commit hook"
-   echo "wcs_test_sasc_render failed ($ErrorString)!"
-   echo "Commit refused."
-   exit 1
-fi
+
+    # Verzeichnis vorbereiten
+    rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
+    mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
+
+    # Remote-Ausfuehrung
+    Error=0
+    ErrorString=""
+    sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && $SSH_COMMAND"
+
+    # Montage der Bilder
+    montage \
+        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
+        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
+        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
+        -label $LABEL ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
+        -geometry 752x480 -tile 2x2 $IMAGE_PREFIX.jpg
+    eog $IMAGE_PREFIX.jpg &
+
+    # Fehlerueberpruefung fuer jede Datei
+    for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
+    do
+
+      # Fuehre den compare-Befehl aus und speichere die Ausgabe in einer Variablen
+#set -x
+      difference=$(compare -metric AE -fuzz 6% test_files/reference/ref_wcs2.031_$file RenderTestImages/$file null: 2>&1)
+
+      # Extrahiere die Differenz von der Ausgabe (da compare Fehlerausgaben als Rueckgabewerte sendet)
+      # In diesem Fall wird die Differenz auf die Standardfehlerausgabe geschrieben, daher "2>&1".
+      # Die Ausgabe ist eine Zahl (die Anzahl der unterschiedlichen Pixel).
+      difference_value=$(echo "$difference" | awk '/^[0-9]+/{print $1}')
+echo "differenz_value=$difference_value"
+      # Vergleiche, ob die Differenz groesser als 10 ist
+      if [ "$(echo "$difference_value > 0" | bc -l)" -ne 0 ]; then
+echo "Diff zu gross"
+        LastError=1
+        Error=$(expr $Error + $LastError)
+
+        if [ $LastError -ne 0 ]; then
+            ErrorString="$ErrorString $file"
+        fi
+else
+echo "Diff nicht gruesser 10"
+      fi
+#set +x
+    done
+
+    # Fehlerbehandlung
+    if [ $Error -ne 0 ]; then
+        echo "Local pre-commit hook"
+        echo "$SSH_COMMAND failed ($ErrorString)!"
+#        echo "Commit refused."
+         echo "ignored for now, test will move later."
+#        exit 1
+    fi
 }
 
-
+################################################################
+function RenderTest_WinUAE_SASC {
+    RenderTest_Generic "SAS/C" "wcs_test_sasc_render" "BigSasC" "ref"
+}
 
 ################################################################
 function RenderTest_WinUAE_68020 {
-# Render-Test 68020
-
-if [ -z $WINUAEIP ]; then
-   CheckSshWinUAE
-fi
-
-rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-
-# This runs the complete program. At the end we have the rendered example images that need to be checked.
-Error=0
-ErrorString=""
-sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && test_68020_render/wcs_test_68020_render"
-
-montage \
-        -label 68020 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
-        -label 68020 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
-        -label 68020 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
-        -label 68020 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
-        -geometry 752x480 -tile 2x2 Big68020.jpg
-eog Big68020.jpg &
-
-
-
-for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
-do
-  #  cmp ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file ~/Desktop/SelcoGit/3DNature/Amiga/test_files/reference/ref_$file
-  #display ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file  # just diplay each rendered file for now
-    LastError=$?
-    Error=$(expr $Error + $LastError)
-    
-    if [ $LastError -ne 0 ]; then
-        ErrorString="$ErrorString $file"
-    fi
-done
-
-# Wenn Fehler aufgetreten sind, gebe eine Fehlermeldung aus
-if [ $Error -ne 0 ]; then
-   echo "Local pre-commit hook"
-   echo "test_68020_render/wcs_test_68020_render failed ($ErrorString)!"
-   echo "Commit refused."
-   exit 1
-fi
+    RenderTest_Generic "68020" "test_68020_render/wcs_test_68020_render" "Big68020" "ref"
 }
 
 ################################################################
 function RenderTest_WinUAE_68020_60 {
-# Render-Test 68020-60
-
-if [ -z $WINUAEIP ]; then
-   CheckSshWinUAE
-fi
-
-rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-
-# This runs the complete program. At the end we have the rendered example images that need to be checked.
-Error=0
-ErrorString=""
-sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && test_68020-60_render/wcs_test_68020-60_render"
-
-montage \
-        -label 68020_60 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
-        -label 68020_60 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
-        -label 68020_60 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
-        -label 68020_60 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
-        -geometry 752x480 -tile 2x2 Big68020_60.jpg
-eog Big68020_60.jpg &
-
-
-
-for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
-do
-  #  cmp ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file ~/Desktop/SelcoGit/3DNature/Amiga/test_files/reference/ref_$file
-  #display ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file  # just diplay each rendered file for now
-    LastError=$?
-    Error=$(expr $Error + $LastError)
-
-    if [ $LastError -ne 0 ]; then
-        ErrorString="$ErrorString $file"
-    fi
-done
-
-# Wenn Fehler aufgetreten sind, gebe eine Fehlermeldung aus
-if [ $Error -ne 0 ]; then
-   echo "Local pre-commit hook"
-   echo "test_68020-060_render/wcs_test_68020-60_render failed ($ErrorString)!"
-   echo "Commit refused."
-   exit 1
-fi
+    RenderTest_Generic "68020_60" "test_68020-60_render/wcs_test_68020-60_render" "Big68020_60" "ref"
 }
 
 ################################################################
 function RenderTest_WinUAE_68040 {
-# Render-Test 68040
-
-if [ -z $WINUAEIP ]; then
-   CheckSshWinUAE
-fi
-
-rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-
-# This runs the complete program. At the end we have the rendered example images that need to be checked.
-Error=0
-ErrorString=""
-sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && test_68040_render/wcs_test_68040_render"
-
-montage \
-        -label 68040 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
-        -label 68040 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
-        -label 68040 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
-        -label 68040 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
-        -geometry 752x480 -tile 2x2 Big68040.jpg
-eog Big68040.jpg &
-
-for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
-do
-  #    cmp ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file ~/Desktop/SelcoGit/3DNature/Amiga/test_files/reference/ref_$file
-  #display ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file  # just diplay each rendered file for now
-    LastError=$?
-    Error=$(expr $Error + $LastError)
-
-    if [ $LastError -ne 0 ]; then
-        ErrorString="$ErrorString $file"
-    fi
-done
-
-# Wenn Fehler aufgetreten sind, gebe eine Fehlermeldung aus
-if [ $Error -ne 0 ]; then
-   echo "Local pre-commit hook"
-   echo "test_68040_render/wcs_test_68040_render failed ($ErrorString)!"
-   echo "Commit refused."
-   exit 1
-fi
+    RenderTest_Generic "68040" "test_68040_render/wcs_test_68040_render" "Big68040" "ref"
 }
-
 
 ################################################################
 function RenderTest_WinUAE_68060 {
-# Render-Test 68060
-
-if [ -z $WINUAEIP ]; then
-   CheckSshWinUAE
-fi
-
-rm -rf ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-mkdir -p ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages
-
-# This runs the complete program. At the end we have the rendered example images that need to be checked.
-Error=0
-ErrorString=""
-sshpass -p amigarulez! ssh -p 22222 ich@"$WINUAEIP" "vbox:SelcoGit/3DNature/amiga && stack 100000 && test_68060_render/wcs_test_68060_render"
-
-montage \
-        -label 68060 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/CanyonSet000 \
-        -label 68060 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/RMNP000 \
-        -label 68060 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/DemoFrame001 \
-        -label 68060 ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/WorldTest001 \
-        -geometry 752x480 -tile 2x2 Big68060.jpg
-eog Big68060.jpg &
-
-
-
-for file in "RMNP000" "CanyonSet000" "DemoFrame001" "WorldTest001"
-do
-  #    cmp ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file ~/Desktop/SelcoGit/3DNature/Amiga/test_files/reference/ref_$file
-  #display ~/Desktop/SelcoGit/3DNature/Amiga/RenderTestImages/$file  # just diplay each rendered file for now
-    LastError=$?
-    Error=$(expr $Error + $LastError)
-
-    if [ $LastError -ne 0 ]; then
-        ErrorString="$ErrorString $file"
-    fi
-done
-
-# Wenn Fehler aufgetreten sind, gebe eine Fehlermeldung aus
-if [ $Error -ne 0 ]; then
-   echo "Local pre-commit hook"
-   echo "test_68060_render/wcs_test_68060_render failed ($ErrorString)!"
-   echo "Commit refused."
-   exit 1
-fi
+    RenderTest_Generic "68060" "test_68060_render/wcs_test_68060_render" "Big68060" "ref"
 }
-
 
 #######################################################################################
 
@@ -438,9 +296,9 @@ else
     TestConvertOnWinUAE68020
     TestConvertOnArosI386
     TestConvertOnArosX86_64
-    RenderTest_WinUAE_SASC
-    RenderTest_WinUAE_68020
+    RenderTest_WinUAE_SASC       # 6%
+    RenderTest_WinUAE_68020      # schwarze Sonne/Mond
     RenderTest_WinUAE_68020_60
-    RenderTest_WinUAE_68040
+    RenderTest_WinUAE_68040      # schwarze Sonne/Mond
     RenderTest_WinUAE_68060
 fi
